### ISSUE TITLE
`TypeError: this.config.vehicles is not iterable` (possibly due to no car linked in Bluelink)

### ISSUE THREAD

**Issue by MchlLyn** [athal7/homebridge-hyundai-bluelink#142]
**Describe The Bug:**
`TypeError: this.config.vehicles is not iterable` shown in logfile (possibly due to no car linked in Bluelink)

**To Reproduce:**
Install plugin and configure as normal (credentials, pin, etc.)

**Expected behavior:**
I'm still waiting for my new Hyundai Tucson but already created a Bluelink account and installed this plugin. I think/assume this error is caused by the absence of a vehicle in Bluelink. If this is the case then it's a minor esthetic issue (which could be fixed by logging 'No car registered in Bluelink' or something like that :)

**Logs:**

```
 TypeError: this.config.vehicles is not iterable
    at ae.<anonymous> (/homebridge/node_modules/homebridge-hyundai-bluelink/src/platform.ts:68:51)
    at ae.emit (node:events:520:28)
    at ae.<anonymous> (/homebridge/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:51741)
    at Generator.next (<anonymous>)
    at s (/homebridge/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:85)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Plugin Config:**
```json
        {
            "credentials": {
                "username": "hidden",
                "password": "hidden",
                "region": "EU",
                "brand": "hyundai",
                "pin": "hidden"
            },
            "remoteStart": {
                "airCtrl": true,
                "heating1": true,
                "defrost": true,
                "igniOnDuration": 15
            },
            "platform": "Hyundai"
        }
```

**Screenshots:**
n/a

**Environment:**

* **Plugin Version**: 1.4.1
* **Homebridge Version**: 1.4.0
* **Operating System**: Docker

**Comment by MchlLyn** [comment]
A registered car is required in Bluelink for this plugin to work, which makes sense. Therefore it's not really a bug, just something one should know. Closing this issue.
