### ISSUE TITLE
Kia Proceed GT doesn't work

### ISSUE THREAD

**Issue by baseship** [athal7/homebridge-hyundai-bluelink#168]
Homebridge, Node and NPM are on actually versions. Kia Proceed GT is three month old (new car)

[27.4.2022, 23:49:52] [Hyundai] discoverDevices Error Error: Constructor Kia is not managed.
    at E (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:4193)
    at new ie (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:34890)
    at new se (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:50758)
    at HyundaiPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/src/platform.ts:65:20)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/src/platform.ts:39:14)
    at HomebridgeAPI.emit (node:events:539:35)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)

It seems like a problem with autorisation - Any ideas?

**Comment by justindixson** [comment]
Same issue when trying it with a Kia K5

`[homebridge-hyundai-bluelink] discoverDevices Error Error: Constructor kia is not managed.
    at /homebridge/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:12469
    at new j (/homebridge/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:12517)
    at new ae (/homebridge/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:51184)
    at HyundaiPlatform.discoverDevices (/homebridge/node_modules/homebridge-hyundai-bluelink/src/platform.ts:65:20)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-hyundai-bluelink/src/platform.ts:39:14)
    at HomebridgeAPI.emit (node:events:527:28)
    at HomebridgeAPI.signalFinished (/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/homebridge/node_modules/homebridge/src/childBridgeFork.ts:189:14)`

**Comment by b4rk13** [comment]
Bump. Same issue when trying with a 2022 Kia Stinger:

`[01/09/2022, 21:23:141 [Hyundai] discoverDevices Error Error: Constructor kia is not managed.
     at /usr/local/lib/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.is:17:12469
     at new j (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:12517)
     at new ae (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:51184)
     at HyundaiPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/src/platform.ts:65:20)
     at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/src/platform.ts:39:14)
     at HomebridgeAPI.emit (node:events:532:35)
     at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
     at server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:190:14) `

**Comment by athomann** [comment]
I believe this is related to lack of US support in bluelinky https://github.com/Hacksore/bluelinky/issues/135
