### ISSUE TITLE
Cannot read property 'evStatus' of undefined

### ISSUE THREAD

**Issue by cirrusflyer** [athal7/homebridge-hyundai-bluelink#18]
**Describe The Bug:**
getting these errors on a 2016 Hyundai Sonata Hybrid:

**To Reproduce:**
added plugin and attempted to use.

**Expected behavior:**
car should lock or start

**Logs:**

[5/7/2021, 12:43:55 PM] [Hyundai] Status fetch error TypeError: Cannot read property 'evStatus' of undefined
    at D.<anonymous> (/homebridge/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:142479)
    at Generator.next (<anonymous>)
    at p (/homebridge/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:85)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Plugin Config:**

```json
        {
            "credentials": {
                "username": "XXXXXXXXXXX",
                "password": "XXXXXX",
                "region": "US",
                "brand": "hyundai",
                "pin": "XXXXX"
            },
            "vehicles": [
                {
                    "vin": "XXXXXXXXXXXXXXXXXX",
                    "maxRange": 652
                }
            ],
            "remoteStart": {
                "cool": true,
                "heat": false,
                "defrost": false,
                "igniOnDuration": 15
            },
            "platform": "Hyundai"
        }
```
**Environment:**

* **Plugin Version**: 1.3.4
* **Homebridge Version**: 1.3.4
* **Node.js Version**: 14.16.1
* **NPM Version**: 6.14.12
* **Operating System**: Docker Alpine Linux (3.12.6)

**Comment by athal7** [comment]
This looks like an issue with the [bluelinky](https://github.com/Hacksore/bluelinky) dependency
