### ISSUE TITLE
Bluelink plugin suddenly stopped working

### ISSUE THREAD

**Issue by markp734** [athal7/homebridge-hyundai-bluelink#351]
Hi, all was working fine until a few days ago and now I get a whole long list of errors when the plugin starts. I have tried resetting the PIN and the password but this has not worked. Any help gratefully received.

**Logs:**
21/04/2023, 12:08:23Hyundai Bluelink Bridge starting
21/04/2023, 12:08:27Hyundai Bluelink BridgeLoaded plugin 'homebridge-hyundai-bluelink'
21/04/2023, 12:08:27Hyundai Bluelink BridgeLoading 1 platforms...
21/04/2023, 12:08:27Hyundai Bluelink BridgeHyundaiLoading accessory from cache: TUCSON
21/04/2023, 12:08:27Hyundai Bluelink BridgeBridge is running on port 51916.
21/04/2023, 12:08:31Hyundai Bluelink BridgeHyundaiERRORClient Error R [ManagedBluelinkyError]: @EuropeController.login: [400] Bad Request on [POST] https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin - {"errId":"1783a5ee-7cc2-49f7-8669-3d6a74744e4f","errCode":"4003","errMsg":"Invalid values"}
    at U (/var/lib/hoobs/hyundaibluelinkbridge/node_modules/bluelinky/dist/index.js:17:11700)
    at ne.<anonymous> (/var/lib/hoobs/hyundaibluelinkbridge/node_modules/bluelinky/dist/index.js:17:39834)
    at Generator.throw (<anonymous>)
    at a (/var/lib/hoobs/hyundaibluelinkbridge/node_modules/bluelinky/dist/index.js:17:136)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  source: GotError [HTTPError]: Response code 400 (Bad Request)
      at EventEmitter.<anonymous> (/var/lib/hoobs/hyundaibluelinkbridge/node_modules/got/source/as-promise.js:74:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    host: 'prd.eu-ccapi.hyundai.com:8080',
    hostname: 'prd.eu-ccapi.hyundai.com',
    method: 'POST',
    path: '/api/v1/user/signin',
    socketPath: undefined,
    protocol: 'https:',
    url: 'https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin',
    gotOptions: {
      path: '/api/v1/user/signin',
      protocol: 'https:',
      slashes: true,
      auth: null,
      host: 'prd.eu-ccapi.hyundai.com:8080',
      port: '8080',
      hostname: 'prd.eu-ccapi.hyundai.com',
      hash: null,
      search: null,
      query: null,
      pathname: '/api/v1/user/signin',
      href: 'https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin',
      retry: [Object],
      headers: [Object],
      hooks: [Object],
      decompress: true,
      throwHttpErrors: true,
      followRedirect: true,
      stream: false,
      form: false,
      json: true,
      cache: false,
      useElectronNet: false,
      method: 'POST',
      body: '{"email":"markpincombe@sky.com","password":"Molly&23"}',
      cookieJar: [CookieJar]
    },
    statusCode: 400,
    statusMessage: 'Bad Request',
    headers: {
      'ccsp-request-id': '1783a5ee-7cc2-49f7-8669-3d6a74744e4f',
      'ccsp-span-id': '',
      'content-length': '92',
      'content-type': 'application/json',
      date: 'Fri, 21 Apr 2023 11:08:31 GMT',
      vary: 'Origin',
      'x-ratelimit-limit': '0',
      'x-ratelimit-remaining': '0',
      'x-ratelimit-reset': '0',
      connection: 'close',
      'set-cookie': [Array]
    },
    body: {
      errId: '1783a5ee-7cc2-49f7-8669-3d6a74744e4f',
      errCode: '4003',
      errMsg: 'Invalid values'
    }
  }
}
21/04/2023, 12:08:31hyundaibluelinkbridge stopping
21/04/2023, 12:08:37Hyundai Bluelink Bridge starting
21/04/2023, 12:08:41Hyundai Bluelink BridgeLoaded plugin 'homebridge-hyundai-bluelink'
21/04/2023, 12:08:41Hyundai Bluelink BridgeLoading 1 platforms...
21/04/2023, 12:08:41Hyundai Bluelink BridgeHyundaiLoading accessory from cache: TUCSON
21/04/2023, 12:08:41Hyundai Bluelink BridgeBridge is running on port 51916.
21/04/2023, 12:08:43Hyundai Bluelink BridgeHyundaiERRORClient Error R [ManagedBluelinkyError]: @EuropeController.login: [400] Bad Request on [POST] https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin - {"errId":"adecce01-db18-4260-8054-236c577c5cc1","errCode":"4003","errMsg":"Invalid values"}
    at U (/var/lib/hoobs/hyundaibluelinkbridge/node_modules/bluelinky/dist/index.js:17:11700)
    at ne.<anonymous> (/var/lib/hoobs/hyundaibluelinkbridge/node_modules/bluelinky/dist/index.js:17:39834)
    at Generator.throw (<anonymous>)
    at a (/var/lib/hoobs/hyundaibluelinkbridge/node_modules/bluelinky/dist/index.js:17:136)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  source: GotError [HTTPError]: Response code 400 (Bad Request)
      at EventEmitter.<anonymous> (/var/lib/hoobs/hyundaibluelinkbridge/node_modules/got/source/as-promise.js:74:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    host: 'prd.eu-ccapi.hyundai.com:8080',
    hostname: 'prd.eu-ccapi.hyundai.com',
    method: 'POST',
    path: '/api/v1/user/signin',
    socketPath: undefined,
    protocol: 'https:',
    url: 'https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin',
    gotOptions: {
      path: '/api/v1/user/signin',
      protocol: 'https:',
      slashes: true,
      auth: null,
      host: 'prd.eu-ccapi.hyundai.com:8080',
      port: '8080',
      hostname: 'prd.eu-ccapi.hyundai.com',
      hash: null,
      search: null,
      query: null,
      pathname: '/api/v1/user/signin',
      href: 'https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin',
      retry: [Object],
      headers: [Object],
      hooks: [Object],
      decompress: true,
      throwHttpErrors: true,
      followRedirect: true,
      stream: false,
      form: false,
      json: true,
      cache: false,
      useElectronNet: false,
      method: 'POST',
      body: '{"email":"***","password":"***"}',
      cookieJar: [CookieJar]
    },
    statusCode: 400,
    statusMessage: 'Bad Request',
    headers: {
      'ccsp-request-id': 'adecce01-db18-4260-8054-236c577c5cc1',
      'ccsp-span-id': '',
      'content-length': '92',
      'content-type': 'application/json',
      date: 'Fri, 21 Apr 2023 11:08:43 GMT',
      vary: 'Origin',
      'x-ratelimit-limit': '0',
      'x-ratelimit-remaining': '0',
      'x-ratelimit-reset': '0',
      connection: 'close',
      'set-cookie': [Array]
    },
    body: {
      errId: 'adecce01-db18-4260-8054-236c577c5cc1',
      errCode: '4003',
      errMsg: 'Invalid values'
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by andypiper** [comment]
Same issue, and I notice that you are also in Europe (based on the EuropeController call in the log above). I wonder if they changed something recently.

**Comment by fratinize** [comment]
I'm in the us and am getting similar error
