### ISSUE TITLE
Crashed after 1.4.8 update

### ISSUE THREAD

**Issue by kaskoo** [athal7/homebridge-hyundai-bluelink#356]
**Describe The Bug:**

The plugin crashes after restart.

**To Reproduce:**

Run it.

**Expected behavior:**

Get the plugin up and running.

**Logs:**
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/node_modules/got/dist/source/index.js from /var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/node_modules/bluelinky2/dist/index.js not supported.
Instead change the require of /var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/node_modules/got/dist/source/index.js in /var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/node_modules/bluelinky2/dist/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/node_modules/bluelinky2/dist/index.js:2:20)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/dist/platform.js:43:36)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/dist/index.js:3:18)
    at Plugin.load (/var/lib/homebridge/node_modules/homebridge/lib/plugin.js:174:108)
    at ChildBridgeFork.loadPlugin (/var/lib/homebridge/node_modules/homebridge/lib/childBridgeFork.js:75:27)
```

**Plugin Config:**

        {
            "credentials": {
                "username": "x@xxx.xx",
                "password": "xx",
                "region": "EU",
                "brand": "hyundai",
                "pin": "xxxx"
            },
            "vehicles": [
                {
                    "vin": "KMHK381xxxxxxxx",
                    "maxRange": 250
                }
            ],
            "remoteStart": {
                "airCtrl": true,
                "heating1": true,
                "defrost": true,
                "igniOnDuration": 5
            },
            "_bridge": {
                "username": "xx:xx:xx:xx",
                "port": 49xxx
            },
            "platform": "Hyundai"
        }

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.4.8
* **Homebridge Version**: 1.7.0
* **Node.js Version**: v20.9.0
* **NPM Version**: 10.1.0
* **Operating System**: Debian

**Comment by pims31** [comment]
I guess I have the same issue as here above.

- **Describe The Bug:**

The plugin crashes after restart.

- **To Reproduce:**

Run it.

- **Expected behavior:**

Get the plugin up and running.

- **Logs:**

```
ERROR LOADING PLUGIN homebridge-hyundai-bluelink2:
Error [ERR_REQUIRE_ESM]: require() of ES Module /var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/node_modules/got/dist/source/index.js from /var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/node_modules/bluelinky2/dist/index.js not supported.
Instead change the require of /var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/node_modules/got/dist/source/index.js in /var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/node_modules/bluelinky2/dist/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/node_modules/bluelinky2/dist/index.js:2:20)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/dist/platform.js:43:36)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-hyundai-bluelink2/dist/index.js:3:18)
    at Plugin.load (/var/lib/homebridge/node_modules/homebridge/lib/plugin.js:174:108)
    at PluginManager.initializeInstalledPlugins (/var/lib/homebridge/node_modules/homebridge/lib/pluginManager.js:72:30)
    at async Server.start (/var/lib/homebridge/node_modules/homebridge/lib/server.js:131:9)
```

- **Plugin Config:**

```
        {
            "credentials": {
                "username": "XXX@XXX",
                "password": "XXX",
                "region": "EU",
                "brand": "hyundai",
                "pin": "XXX"
            },
            "vehicles": [
                {
                    "vin": "XXX"
                }
            ],
            "remoteStart": {
                "airCtrl": false,
                "heating1": false,
                "defrost": false,
                "igniOnDuration": 5
            },
            "platform": "Hyundai"
       }
```

- **Environment:**

Plugin Version: 1.4.8
Homebridge Version: 1.7.0
Node.js Version: v20.9.0
Operating System: Raspbian GNU/Linux Bullseye (11)


Is there something I need to do?

Thank you in advance for your support.

**Comment by djjuice** [comment]
nothing can be done... right on the readme, this is no longer maintained
